# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipresource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddr',
            name='assign',
            field=models.BooleanField(verbose_name='\u662f\u5426\u5206\u914d'),
        ),
    ]
