# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipresource', '0002_auto_20160820_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pos',
            name='comment',
        ),
        migrations.AddField(
            model_name='pos',
            name='desc',
            field=models.TextField(default=0, verbose_name='\u63cf\u8ff0'),
            preserve_default=False,
        ),
    ]
