# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipresource', '0003_auto_20160821_0903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddr',
            options={'ordering': ['ip'], 'verbose_name': 'IP\u4fe1\u606f', 'verbose_name_plural': 'IP\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='pos',
            options={'ordering': ['name'], 'verbose_name': '\u4f4d\u7f6e\u4fe1\u606f', 'verbose_name_plural': '\u4f4d\u7f6e\u4fe1\u606f'},
        ),
    ]
