# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50, verbose_name=b'\xe9\x83\xa8\xe9\x97\xa8')),
                ('remark', models.TextField(blank=True, verbose_name=b'\xe9\x83\xa8\xe9\x97\xa8\xe6\x8f\x8f\xe8\xbf\xb0')),
            ],
            options={
                'verbose_name': '\u90e8\u95e8',
                'verbose_name_plural': '\u90e8\u95e8',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(blank=True, null=True, unique=True, verbose_name=b'\xe7\x89\x88\xe6\x9c\xac\xe5\x8f\xb7')),
                ('content', models.TextField(blank=True, null=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe8\xaf\xb4\xe6\x98\x8e')),
                ('issue_type', models.BooleanField(default=True, verbose_name=b'\xe6\x99\xae\xe9\x80\x9a\xe4\xb8\x8a\xe7\xba\xbf')),
                ('op_time', models.DateField(blank=True, null=True, verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe6\x97\xa5\xe6\x9c\x9f')),
                ('rec_user', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe5\xbd\x95\xe5\x85\xa5\xe4\xba\xba\xe5\x91\x98')),
                ('rec_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe5\xbd\x95\xe5\x85\xa5\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name': '\u7cfb\u7edf\u66f4\u65b0\u64cd\u4f5c\u8bb0\u5f55',
                'verbose_name_plural': '\u7cfb\u7edf\u66f4\u65b0\u64cd\u4f5c\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name=b'\xe5\xa7\x93\xe5\x90\x8d')),
                ('mobile', models.CharField(max_length=40, verbose_name=b'\xe6\x89\x8b\xe6\x9c\xba')),
                ('email', models.EmailField(max_length=254, verbose_name=b'\xe9\x82\xae\xe7\xae\xb1')),
                ('isvalid', models.BooleanField(default=True, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe5\x9c\xa8\xe8\x81\x8c')),
                ('remark', models.TextField(blank=True, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updateOp.Dept', verbose_name=b'\xe9\x83\xa8\xe9\x97\xa8')),
            ],
            options={
                'verbose_name': '\u5458\u5de5\u4fe1\u606f',
                'verbose_name_plural': '\u5458\u5de5\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name=b'\xe4\xba\xa7\xe5\x93\x81\xe5\x90\x8d\xe7\xa7\xb0')),
                ('remark', models.TextField(blank=True, verbose_name=b'\xe4\xba\xa7\xe5\x93\x81\xe8\xaf\xb4\xe6\x98\x8e')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u4fe1\u606f',
                'verbose_name_plural': '\u4ea7\u54c1\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='operator',
            field=models.ManyToManyField(related_name='operator_person', to='updateOp.Persons', verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe5\x91\x98'),
        ),
        migrations.AddField(
            model_name='issue',
            name='prod',
            field=models.ManyToManyField(to='updateOp.Prod', verbose_name=b'\xe4\xba\xa7\xe5\x93\x81'),
        ),
        migrations.AddField(
            model_name='issue',
            name='report_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_to_person', to='updateOp.Persons', verbose_name=b'\xe6\xb1\x87\xe6\x8a\xa5\xe4\xba\xba'),
        ),
        migrations.AddField(
            model_name='issue',
            name='req_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_from_person', to='updateOp.Persons', verbose_name=b'\xe9\x9c\x80\xe6\xb1\x82\xe6\x8f\x90\xe5\x87\xba\xe8\x80\x85'),
        ),
    ]
