# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbserver',
            name='pos',
            field=models.CharField(default=0, max_length=30, verbose_name='\u670d\u52a1\u5668\u4f4d\u7f6e'),
            preserve_default=False,
        ),
    ]
