# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u516c\u53f8\u540d\u79f0')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u516c\u53f8\u5730\u5740')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u59d3\u540d')),
                ('sex', models.NullBooleanField(verbose_name='\u6027\u522b')),
                ('dept', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u90e8\u95e8')),
                ('contact', models.CharField(blank=True, max_length=150, null=True, verbose_name='\u8054\u7cfb\u65b9\u5f0f')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addressbook.Company', verbose_name='\u516c\u53f8')),
            ],
        ),
    ]
