# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': '\u516c\u53f8\u4fe1\u606f', 'verbose_name_plural': '\u516c\u53f8\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='persons',
            options={'ordering': ['name'], 'verbose_name': '\u4eba\u5458\u4fe1\u606f', 'verbose_name_plural': '\u4eba\u5458\u4fe1\u606f'},
        ),
        migrations.AddField(
            model_name='company',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u516c\u53f8\u7535\u8bdd'),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u516c\u53f8\u4e3b\u9875'),
        ),
    ]
