# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='\u5e94\u7528\u540d\u79f0')),
                ('language', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u5f00\u53d1\u8bed\u8a00')),
                ('env', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5f00\u53d1\u73af\u5883')),
                ('plugs', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6240\u9700\u63d2\u4ef6')),
                ('requires', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4f9d\u8d56')),
                ('config_file', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u914d\u7f6e\u6587\u4ef6')),
                ('function', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u529f\u80fd')),
                ('teams', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5f00\u53d1\u56e2\u961f')),
                ('dev_time', models.DateField(blank=True, null=True, verbose_name='\u5f00\u53d1\u65f6\u95f4')),
                ('version', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7248\u672c\u53f7')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u8054\u7cfb\u4eba')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u5e94\u7528\u4fe1\u606f',
                'verbose_name_plural': '\u5e94\u7528\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='\u4e1a\u52a1\u540d\u79f0')),
                ('documents', models.FileField(blank=True, null=True, upload_to='./uploads/%Y/%m/%d/', verbose_name='\u4e1a\u52a1\u8bf4\u660e\u6587\u6863')),
                ('contacts', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4e1a\u52a1\u8054\u7cfb\u4eba')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='\u4e1a\u52a1\u7b80\u4ecb')),
                ('online', models.DateField(blank=True, null=True, verbose_name='\u4e0a\u7ebf\u65f6\u95f4')),
                ('architecture', models.ImageField(blank=True, null=True, upload_to='./uploads/%Y/%m/%d/', verbose_name='\u7cfb\u7edf\u67b6\u6784\u56fe')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u4e1a\u52a1\u4fe1\u606f',
                'verbose_name_plural': '\u4e1a\u52a1\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='\u90e8\u7f72\u540d\u79f0')),
                ('paths', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u90e8\u7f72\u8def\u5f84')),
                ('users', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7cfb\u7edf\u7528\u6237')),
                ('boot_scripts', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u542f\u52a8\u811a\u672c')),
                ('ports', models.IntegerField(blank=True, null=True, verbose_name='\u7aef\u53e3\u53f7')),
                ('logs', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u65e5\u5fd7\u8def\u5f84')),
                ('documents', models.FileField(blank=True, null=True, upload_to='./uploads/%Y/%m/%d/', verbose_name='\u90e8\u7f72\u6587\u6863')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u90e8\u7f72\u4eba')),
                ('times', models.DateField(blank=True, null=True, verbose_name='\u90e8\u7f72\u65f6\u95f4')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appinfo.App', verbose_name='\u5e94\u7528\u540d\u79f0')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u90e8\u7f72\u4fe1\u606f',
                'verbose_name_plural': '\u90e8\u7f72\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='\u670d\u52a1\u5668\u540d\u79f0')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u670d\u52a1\u5668IP')),
                ('zone', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u7f51\u7edc\u533a\u57df')),
                ('sn', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7f16\u53f7')),
                ('manufacturer', models.CharField(blank=True, max_length=25, null=True, verbose_name='\u54c1\u724c')),
                ('mod', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u578b\u53f7')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u673a\u5668\u7c7b\u578b')),
                ('cpu_freq', models.CharField(blank=True, max_length=255, null=True, verbose_name='CPU')),
                ('cpu_core', models.IntegerField(blank=True, null=True, verbose_name='\u6838\u6570')),
                ('mem', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5185\u5b58\u5927\u5c0f')),
                ('disk', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u786c\u76d8\u5927\u5c0f')),
                ('raid', models.CharField(blank=True, max_length=20, null=True, verbose_name='RAID')),
                ('size', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u670d\u52a1\u5668\u5c3a\u5bf8')),
                ('buy_date', models.DateField(blank=True, null=True, verbose_name='\u8d2d\u4e70\u65f6\u95f4')),
                ('contact', models.CharField(blank=True, max_length=25, null=True, verbose_name='\u8054\u7cfb\u4eba')),
                ('factory_phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('guaranteed', models.SmallIntegerField(blank=True, null=True, verbose_name='\u662f\u5426\u5728\u4fdd')),
                ('cabinet', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u673a\u67dc\u53f7')),
                ('idc', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u673a\u623f')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'ordering': ['ip'],
                'verbose_name': '\u670d\u52a1\u5668\u4fe1\u606f',
                'verbose_name_plural': '\u670d\u52a1\u5668\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='deploy',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appinfo.Server', verbose_name='\u90e8\u7f72\u670d\u52a1\u5668'),
        ),
        migrations.AddField(
            model_name='business',
            name='deploys',
            field=models.ManyToManyField(to='appinfo.Deploy', verbose_name='\u90e8\u7f72'),
        ),
    ]
