# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='architecture',
            field=models.ImageField(blank=True, null=True, upload_to='./uploads/imgs/', verbose_name='\u7cfb\u7edf\u67b6\u6784\u56fe'),
        ),
        migrations.AlterField(
            model_name='business',
            name='documents',
            field=models.TextField(blank=True, null=True, verbose_name='\u4e1a\u52a1\u8bf4\u660e\u6587\u6863'),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='./uploads/docs/deploy/', verbose_name='\u90e8\u7f72\u6587\u6863'),
        ),
    ]
