# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinfo', '0002_auto_20160827_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='plugs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6846\u67b6'),
        ),
        migrations.AlterField(
            model_name='business',
            name='architecture',
            field=models.ImageField(blank=True, null=True, upload_to='./deploy', verbose_name='\u7cfb\u7edf\u67b6\u6784\u56fe'),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='./deploy', verbose_name='\u90e8\u7f72\u6587\u6863'),
        ),
    ]
