# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortmapLanIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_ip', models.CharField(max_length=20, verbose_name='LAN')),
                ('l_name', models.CharField(blank=True, max_length=255, verbose_name='\u670d\u52a1\u5668\u540d\u79f0')),
                ('detail', models.TextField(blank=True, verbose_name='\u8be6\u7ec6\u4fe1\u606f')),
                ('comment', models.TextField(blank=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'ordering': ['l_ip'],
                'verbose_name': '\u5185\u7f51IP',
                'verbose_name_plural': '\u5185\u7f51IP',
            },
        ),
        migrations.CreateModel(
            name='PortmapMaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_port', models.IntegerField(verbose_name='\u5916\u7f51\u7aef\u53e3')),
                ('l_port', models.IntegerField(verbose_name='\u5185\u7f51\u7aef\u53e3')),
                ('comment', models.TextField(verbose_name='\u529f\u80fd\u63cf\u8ff0')),
                ('l_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PortmapLanIp', to='portmap.PortmapLanIp', verbose_name='\u5185\u7f51IP')),
            ],
            options={
                'ordering': ['w_ip', 'w_port', 'l_ip', 'l_port'],
                'verbose_name': '\u7aef\u53e3\u6620\u5c04\u8868',
                'verbose_name_plural': '\u7aef\u53e3\u6620\u5c04\u8868',
            },
        ),
        migrations.CreateModel(
            name='PortmapWanIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_ip', models.CharField(max_length=20, verbose_name='WAN')),
                ('firewall', models.CharField(blank=True, max_length=255, verbose_name='\u9632\u706b\u5899\u540d\u79f0')),
                ('f_location', models.CharField(blank=True, max_length=255, verbose_name='\u9632\u706b\u5899\u4f4d\u7f6e')),
                ('comment', models.TextField(blank=True, max_length=255, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'ordering': ['w_ip'],
                'verbose_name': '\u516c\u7f51IP',
                'verbose_name_plural': '\u516c\u7f51IP',
            },
        ),
        migrations.AddField(
            model_name='portmapmaps',
            name='w_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PortmapWanIp', to='portmap.PortmapWanIp', verbose_name='\u5916\u7f51IP'),
        ),
    ]
