# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortcut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('website', models.NullBooleanField(verbose_name='\u5730\u5740')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u5feb\u6377\u94fe\u63a5',
                'verbose_name_plural': '\u5feb\u6377\u94fe\u63a5',
            },
        ),
    ]
