# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcut', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcut',
            name='website',
            field=models.CharField(default=0, max_length=150, verbose_name='\u94fe\u63a5\u5730\u5740'),
            preserve_default=False,
        ),
    ]
